package org.apache.cxf.transport.http.asyncclient.hc5;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;

import java.util.concurrent.Future;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "EchoService", targetNamespace = "http://www.bccs.uib.no/EchoService.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface EchoService {


    /**
     * Just a simple echo operation that returns the same string that is given to it.
     *
     * @param parameters
     * @return
     *     returns jakarta.xml.ws.Response<org.apache.cxf.transport.http.asyncclient.hc5.SayHiResponse>
     */
    @WebMethod(operationName = "SayHi", action = "http://www.bccs.uib.no/EchoService.wsdl/SayHi")
    public Response<SayHiResponse> sayHiAsync(
            @WebParam(name = "SayHi", targetNamespace = "http://www.bccs.uib.no/EchoService.wsdl", partName = "parameters")
            SayHi parameters);

    /**
     * Just a simple echo operation that returns the same string that is given to it.
     *
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SayHi", action = "http://www.bccs.uib.no/EchoService.wsdl/SayHi")
    public Future<?> sayHiAsync(
            @WebParam(name = "SayHi", targetNamespace = "http://www.bccs.uib.no/EchoService.wsdl", partName = "parameters")
            SayHi parameters,
            @WebParam(name = "SayHiResponse", targetNamespace = "", partName = "asyncHandler")
            AsyncHandler<SayHiResponse> asyncHandler);

    /**
     * Just a simple echo operation that returns the same string that is given to it.
     *
     * @param parameters
     * @return
     *     returns org.apache.cxf.transport.http.asyncclient.hc5.SayHiResponse
     */
    @WebMethod(operationName = "SayHi", action = "http://www.bccs.uib.no/EchoService.wsdl/SayHi")
    @WebResult(name = "SayHiResponse", targetNamespace = "http://www.bccs.uib.no/EchoService.wsdl", partName = "parameters")
    public SayHiResponse sayHi(
            @WebParam(name = "SayHi", targetNamespace = "http://www.bccs.uib.no/EchoService.wsdl", partName = "parameters")
            SayHi parameters);

}